package myPackage;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ranbir
 */
public class registerFrame extends javax.swing.JFrame {

    /**
     * Creates new form registerFrame
     */
    public registerFrame() {
        initComponents();
        int accountID = mainHandler.generateAccountNo();
        accountNum.setText(Integer.toString(accountID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        decor = new javax.swing.JPanel();
        accountNum = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        accountName = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        title9 = new javax.swing.JLabel();
        bankBranchCB = new javax.swing.JComboBox<>();
        title11 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        decor2 = new javax.swing.JPanel();
        accountBalance = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        title6 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        passwordRe = new javax.swing.JPasswordField();
        title10 = new javax.swing.JLabel();
        passwordShowBox = new javax.swing.JCheckBox();
        title12 = new javax.swing.JLabel();
        signIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(70, 144, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        title.setText("Sign Up");

        decor.setBackground(new java.awt.Color(70, 144, 255));

        javax.swing.GroupLayout decorLayout = new javax.swing.GroupLayout(decor);
        decor.setLayout(decorLayout);
        decorLayout.setHorizontalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        decorLayout.setVerticalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        accountNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountNum.setText("12345678");
        accountNum.setEnabled(false);
        accountNum.setSelectionColor(new java.awt.Color(255, 255, 255));

        title2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title2.setText("Account Number");

        title8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title8.setText("Full Name");

        accountName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountName.setSelectionColor(new java.awt.Color(255, 255, 255));

        addressTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addressTF.setSelectionColor(new java.awt.Color(255, 255, 255));
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });

        title9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title9.setText("Address");

        bankBranchCB.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        bankBranchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CB Branch Brampton", "CB Branch Townsvilla", "CB Branch Longtown", "CB Branch Toronto", "CB Branch USA", "CB Branch Mexico" }));
        bankBranchCB.setFocusable(false);

        title11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title11.setText("Bank Branch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bankBranchCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountNum)
                    .addComponent(title8, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(accountName)
                    .addComponent(addressTF)
                    .addComponent(title9, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(title11, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(title8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(title9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(title11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bankBranchCB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 255, 255));
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Commercial Banking™");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        decor2.setBackground(new java.awt.Color(70, 144, 255));

        javax.swing.GroupLayout decor2Layout = new javax.swing.GroupLayout(decor2);
        decor2.setLayout(decor2Layout);
        decor2Layout.setHorizontalGroup(
            decor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        decor2Layout.setVerticalGroup(
            decor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        accountBalance.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        accountBalance.setSelectionColor(new java.awt.Color(255, 255, 255));

        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        title6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title6.setText("Password");

        title7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title7.setText("Account Deposit");

        signUp.setBackground(new java.awt.Color(70, 144, 255));
        signUp.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Sign Up");
        signUp.setFocusable(false);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        passwordRe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        title10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        title10.setText("Re-Enter Password");

        passwordShowBox.setBackground(new java.awt.Color(255, 255, 255));
        passwordShowBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        passwordShowBox.setText("Show Password");
        passwordShowBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordShowBox.setFocusable(false);
        passwordShowBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordShowBoxActionPerformed(evt);
            }
        });

        title12.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        title12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title12.setText("$");

        signIn.setBackground(new java.awt.Color(255, 255, 254));
        signIn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        signIn.setForeground(new java.awt.Color(70, 144, 255));
        signIn.setText("Already Have An Account? Sign In Here");
        signIn.setFocusable(false);
        signIn.setRequestFocusEnabled(false);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(decor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title7, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(signUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password)
                            .addComponent(passwordRe)
                            .addComponent(title10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(passwordShowBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(decor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(title7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(title6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(title10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordRe, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(passwordShowBox)
                .addGap(26, 26, 26)
                .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // Sign Up Button Action
        boolean errorTriggered = false;
        
        int accNo =  Integer.parseInt(accountNum.getText());
        String bankBranch = (String) bankBranchCB.getSelectedItem();
        String accHolderName = "";
        BigDecimal balance = new BigDecimal(0);
        String address = "";
        String pass = "";
        String passRe = "";
        
        // First let's do a soft error check, so that are parameters don't cause an error
        
        // Checking for valid name
        if (accountName.getText().length() >= 1) {
            accHolderName = accountName.getText();
        } else {
            errorTriggered = true;
            JOptionPane.showMessageDialog(
                null, 
                "Invalid Name!\nName's Don't Contain Numbers", 
                "Account Creation Error", 
                JOptionPane.WARNING_MESSAGE
            );
        }
        // Checking for valid balance
        if (accountBalance.getText().length() >= 1) {
            balance = new BigDecimal(accountBalance.getText());
            if (balance.compareTo(BigDecimal.ZERO) <= 0) {
                errorTriggered = true;
                JOptionPane.showMessageDialog(
                    null, 
                    "Deposit Amount Cannot Be Negative!\n[Please Try Again]", 
                    "Account Creation Error", 
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } else {
            errorTriggered = true;
            JOptionPane.showMessageDialog(
                null, 
                "Invalid Account Deposit Balance!\n[Please Try Again]", 
                "Account Creation Error", 
                JOptionPane.WARNING_MESSAGE
            );
        }
        
        // Checking for valid address [xx xxxx
        if (addressTF.getText().length() >= 7) {
            address = addressTF.getText();
        } else {
            errorTriggered = true;
            JOptionPane.showMessageDialog(
                null, 
                "Invalid Address\n\n[Address Format]:\n[Two Numbers][Street, Length Greater Than 3]",
                "Account Creation Error", 
                JOptionPane.WARNING_MESSAGE
            );
        }

        // Checking for valid passwords
        if (password.getText().equals(passwordRe.getText())) {
            if (password.getText().length() >= 8) {
                pass = String.valueOf(password.getPassword());
                passRe = String.valueOf(passwordRe.getPassword());
            } else {
                errorTriggered = true;
               JOptionPane.showMessageDialog(
                       null, 
                       "Invalid Password\n\n[Passmust Must Contain]:\n1 Uppercase, 1 Lowercase, and a Length Greater Than 7", 
                       "Account Creation Error",
                       JOptionPane.WARNING_MESSAGE
               );
            }
        } else {
            errorTriggered = true;
            JOptionPane.showMessageDialog(
                null, 
                "Passwords Don't Match!\n[Please Try Again]", 
                "Account Creation Error", 
                JOptionPane.WARNING_MESSAGE
            );
        }
        
        // Displaying to console
        System.out.println(
        "Account No: " + accNo + "\nAccount Holder's Name: " + accHolderName + "\nBalance: " + balance
        + "\nAddress: " + address + "\nBank Branch: " + bankBranch + "\nPassword: " + pass + "\nPassword Re-Enter: " + passRe + "\n========");

        // Attempting to create an account
        if (errorTriggered == false) {
            String attempt = mainHandler.generateNewUser(accNo, accHolderName, balance, address, pass, bankBranch);
            if (!attempt.equals("Success")) {
                JOptionPane.showMessageDialog(null, attempt, "Account Creation Error", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "You Have Created An Account With Commercial Banking™", "Account Creation Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                loginFrame frame = new loginFrame();
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_signUpActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // Login Button
        // Opens up the Login Frame

        this.setVisible(false);
        loginFrame frame = new loginFrame();
        frame.setVisible(true);

    }//GEN-LAST:event_signInActionPerformed

    private void passwordShowBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordShowBoxActionPerformed
        // Turning our password boxes visble
        if (passwordShowBox.isSelected()) {
            password.setEchoChar((char)0);
            passwordRe.setEchoChar((char)0);
        } else {
            password.setEchoChar('*');
            passwordRe.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordShowBoxActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountBalance;
    private javax.swing.JTextField accountName;
    private javax.swing.JTextField accountNum;
    private javax.swing.JTextField addressTF;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> bankBranchCB;
    private javax.swing.JPanel decor;
    private javax.swing.JPanel decor1;
    private javax.swing.JPanel decor2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordRe;
    private javax.swing.JCheckBox passwordShowBox;
    private javax.swing.JButton signIn;
    private javax.swing.JButton signUp;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title12;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    // End of variables declaration//GEN-END:variables
}
